import = ["~/.config/alacritty/themes/tokyo-night.toml"]
live_config_reload = true

[bell]
animation = "EaseOutExpo"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
style = "Block"
unfocused_hollow = false

[debug]
render_timer = false

[env]
TERM = "xterm-256color"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"


[window]
opacity = 1
decorations = "none"
dynamic_title = true
option_as_alt = "Both"
# startup_mode = "SimpleFullscreen"

[window.padding]
x = 1
y = 1

[font]
size = 16.0
[font.normal]
family = "IosevkaTerm Nerd Font Mono"
style = "Regular"
[font.bold]
family = "IosevkaTerm Nerd Font Mono"
style = "Bold"
[font.italic]
family = "IosevkaTerm Nerd Font Mono"
style = "Italic"
[font.bold_italic]
family = "IosevkaTerm Nerd Font Mono"
style = "Bold Italic"

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[shell]
program = "/opt/homebrew/bin/zellij"
args = ["-l", "welcome"]

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left", mods = "Alt", chars = "\u001BB" },
]
