tap "hudochenkov/sshpass"
brew "ffmpeg"
brew "gnupg"
brew "mas"
brew "pinentry-mac"
brew "poppler"
brew "sops"
brew "xcodegen"
brew "zsh-autosuggestions"
brew "hudochenkov/sshpass/sshpass"
cask "1password"
cask "android-platform-tools"
cask "claude"
cask "cleanshot"
cask "cmux"
cask "codex-app"
cask "conductor"
cask "font-fira-code-nerd-font"
cask "google-chrome"
cask "granola"
cask "insta360-link-controller"
cask "logi-options+"
cask "notion-calendar"
cask "orbstack"
cask "raycast"
cask "rectangle"
cask "slack"
cask "tailscale-app"
cask "wispr-flow"
cask "zoom"
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Xcode", id: 497799835
