tap "drud/ddev"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
brew "bat"
brew "composer"
brew "exa"
brew "git-delta"
brew "mas"
brew "mkcert"
brew "nss"
brew "nvm"
brew "ripgrep"
brew "starship"
brew "terraform"
brew "drud/ddev/ddev"
cask "clipy"
cask "cloudflare-warp"
cask "docker"
cask "font-caskaydia-cove-nerd-font"
cask "google-chrome"
cask "google-drive"
cask "iriunwebcam"
cask "lando"
cask "muzzle"
cask "notion"
cask "rectangle"
cask "rescuetime"
cask "slack"
cask "visual-studio-code"
cask "vlc"
cask "zoom"
mas "MeetingBar", id: 1532419400
mas "Things", id: 904280696
mas "Unsplash Wallpapers", id: 1284863847
