[tools]
atuin = "latest"
cargo-binstall = "latest"
ffmpeg = "latest"
go = "latest"
k9s = "latest"
node = "lts"
python = "3"
terraform = "latest"
uv = "latest"
k6 = "latest"
zola = "latest"
gh = "latest"
helm = "latest"
starship = "latest"
zoxide = "latest"
bat = "latest"
delta = "latest"
ripgrep = "latest"
eza = "latest"
oha = "latest"
xh = "latest"
maven = "latest"
java = "latest"
