[tools]
atuin = "latest"
cargo-binstall = "latest"
ffmpeg = "latest"
go = "latest"
k9s = "latest"
node = "lts"
python = "3"
terraform = "latest"
uv = "latest"
k6 = "latest"
zola = "latest"
gh = "latest"
helm = "latest"
starship = "latest"
zoxide = "latest"
bat = "latest"
delta = "latest"
ripgrep = "latest"
eza = "latest"
oha = "latest"
xh = "latest"
maven = "latest"
java = "latest"
tokei = "latest"
aws-cli = { version = "latest", symlink_bins = "true" }
doggo = "latest"
claude = "latest"
neovim = "latest"
lazygit = "latest"
1password-cli = "latest"
fzf = "latest"
wrangler = "latest"
bun = "latest"
fd = "latest"
"github:agavra/tuicr" = "latest"
"aqua:cloudflare/cloudflared" = "latest"
glow = "latest"
watchexec = "latest"
"aqua:aws/session-manager-plugin" = "1.2.792.0"
"pipx:pgcli" = "4.4.0"
websocat = "1.14.1"
pnpm = "latest"
golangci-lint = "latest"
gcloud = "latest"
pandoc = "3.9.0.2"
