#!/usr/bin/env bash
# Regenerate packages.lock: the evaluated package set for every host.
#
# This exists because a commit once dropped thirteen packages from dev.nix
# as a side effect, and nothing noticed. It passed nix flake check, nix fmt
# and the whole test harness, because a smaller package set is still a valid
# configuration - "does it evaluate" cannot answer "does it still contain
# what it did".
#
# The lock file makes the package set part of the diff. An intentional change
# updates it in the same commit; an accidental one fails CI.
#
# Names only, no versions: versions move on every flake update and would
# make this churn constantly, while the failure mode worth catching is a
# package silently disappearing.
set -euo pipefail

REPO=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)
cd "$REPO"

OUT=packages.lock
{
  echo "# Generated by 'make packages-lock'. Commit changes to this file"
  echo "# alongside the change that caused them."
  echo
  for host in $(nix eval --raw .#darwinConfigurations --apply \
    'h: builtins.concatStringsSep " " (builtins.attrNames h)'); do
    echo "[$host]"
    nix eval --raw ".#darwinConfigurations.$host.config.home-manager.users.skippednote.home.packages" \
      --apply 'ps: builtins.concatStringsSep "\n" (map (p: p.pname or p.name) ps)' |
      grep -vE '^(hm-session-vars\.sh|home-configuration-reference-manpage)$' |
      sort -u
    echo
  done
} >"$OUT"

echo "wrote $OUT ($(grep -cvE '^\[|^#|^$' "$OUT") packages across $(grep -c '^\[' "$OUT") hosts)"
