#!/usr/bin/env bash
# Regenerate packages.lock: the evaluated package set for every host.
#
# This exists because a commit once dropped thirteen packages from dev.nix
# as a side effect, and nothing noticed. It passed nix flake check, nix fmt
# and the whole test harness, because a smaller package set is still a valid
# configuration - "does it evaluate" cannot answer "does it still contain
# what it did".
#
# The lock file makes the package set part of the diff. An intentional change
# updates it in the same commit; an accidental one fails CI.
#
# Names only, no versions: versions move on every flake update and would
# make this churn constantly, while the failure mode worth catching is a
# package silently disappearing.
set -euo pipefail

REPO=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)
cd "$REPO"

OUT=packages.lock
TMP=$(mktemp)
trap 'rm -f "$TMP"' EXIT
{
  echo "# Generated by 'make packages-lock'. Commit changes to this file"
  echo "# alongside the change that caused them."
  echo
  for host in $(nix eval --raw .#darwinConfigurations --apply \
    'h: builtins.concatStringsSep " " (builtins.attrNames h)'); do
    echo "[$host packages]"
    # parseDrvName strips the version from packages that have no pname -
    # python3-3.14.7-env was the one such entry, and it made the lock churn
    # on every python bump, which the header explicitly says it should not.
    nix eval --raw ".#darwinConfigurations.$host.config.home-manager.users.skippednote.home.packages" \
      --apply 'ps: builtins.concatStringsSep "\n" (
        map (p: p.pname or (builtins.parseDrvName p.name).name) ps)' |
      grep -vE '^(hm-session-vars\.sh|home-configuration-reference-manpage)$' |
      sort -u
    echo

    # Homebrew too. cleanup = "zap" means an accidentally deleted cask is
    # uninstalled along with its application support and preferences, and
    # generations do not undo that - so this is the more destructive set of
    # the two, and it was unguarded.
    for opt in brews casks masApps; do
      echo "[$host $opt]"
      nix eval --json ".#darwinConfigurations.$host.config.homebrew.$opt" |
        python3 -c 'import json,sys
d = json.load(sys.stdin)
if isinstance(d, dict):
    for k in sorted(d): print(k)
else:
    for x in d: print(x["name"] if isinstance(x, dict) else x)' | sort -u
      echo
    done
  done
} >"$TMP"
mv "$TMP" "$OUT"

echo "wrote $OUT ($(grep -cvE '^\[|^#|^$' "$OUT") entries across $(grep -c 'packages\]$' "$OUT") hosts)"
