[tools]
atuin = "latest"
cargo-binstall = "latest"
go = "latest"
k9s = "latest"
node = "lts"
python = "3"
terraform = "latest"
uv = "latest"
k6 = "latest"
zola = "latest"
gh = "latest"
helm = "latest"
starship = "latest"
zoxide = "latest"
bat = "latest"
delta = "latest"
ripgrep = "latest"
eza = "latest"
xh = "latest"
maven = "latest"
java = "latest"
tokei = "latest"
aws-cli = { version = "latest", symlink_bins = "true" }
"github:mr-karan/doggo" = "latest"
claude = "latest"
neovim = "latest"
lazygit = "latest"
1password-cli = "latest"
fzf = "latest"
wrangler = "latest"
bun = "latest"
fd = "latest"
"aqua:cloudflare/cloudflared" = "latest"
glow = "latest"
golangci-lint = "latest"
dust = "latest"
rtk = "latest"
ansible-core = "latest"
dbmate = "latest"
protoc = "latest"
gcloud = "latest"
android-sdk = "latest"
"github:upsun/cli" = "latest"
cloud-sql-proxy = "latest"
"github:tconbeer/harlequin" = "latest"
aws-vault = "latest"
pi = "latest"
codex = "latest"
sops = "latest"
"github:googleworkspace/cli" = "latest"
"github:ddev/ddev" = "latest"

[settings]

[settings.github]
credential_command = "gh auth token"
